services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        networks:
            - laravel
        env_file:
            - .env

    db:
        image: mysql:8.0
        container_name: todo_db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: todo_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: laravel_password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel

volumes:
    db_data:

networks:
    laravel:
